version: '3.8'

services:
  # Backend Application
  backend:
    build: .
    container_name: portfolio-backend
    restart: unless-stopped
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://nicolaananda:Kotakediri1@personal.2rijaws.mongodb.net/?retryWrites=true&w=majority&appName=Personal
      - PORT=5002
      - JWT_SECRET=secret-key
      - JWT_REFRESH_SECRET=secret-key
    volumes:
      - ./logs:/app/logs
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
